//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityMoveitPlanningInterface
{
    [Serializable]
    public class ExecutePathResponse : Message
    {
        public const string k_RosMessageName = "unity_moveit_planning_interface/ExecutePath";
        public override string RosMessageName => k_RosMessageName;

        public bool finished;

        public ExecutePathResponse()
        {
            this.finished = false;
        }

        public ExecutePathResponse(bool finished)
        {
            this.finished = finished;
        }

        public static ExecutePathResponse Deserialize(MessageDeserializer deserializer) => new ExecutePathResponse(deserializer);

        private ExecutePathResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.finished);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.finished);
        }

        public override string ToString()
        {
            return "ExecutePathResponse: " +
            "\nfinished: " + finished.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
