//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityMoveitPlanningInterface
{
    [Serializable]
    public class MoveToJointStateResponse : Message
    {
        public const string k_RosMessageName = "unity_moveit_planning_interface/MoveToJointState";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public MoveToJointStateResponse()
        {
            this.success = false;
        }

        public MoveToJointStateResponse(bool success)
        {
            this.success = success;
        }

        public static MoveToJointStateResponse Deserialize(MessageDeserializer deserializer) => new MoveToJointStateResponse(deserializer);

        private MoveToJointStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "MoveToJointStateResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
