//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityMoveitPlanningInterface
{
    [Serializable]
    public class MoveToPoseStateRequest : Message
    {
        public const string k_RosMessageName = "unity_moveit_planning_interface/MoveToPoseState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg endEffecttorPose;

        public MoveToPoseStateRequest()
        {
            this.endEffecttorPose = new Geometry.PoseMsg();
        }

        public MoveToPoseStateRequest(Geometry.PoseMsg endEffecttorPose)
        {
            this.endEffecttorPose = endEffecttorPose;
        }

        public static MoveToPoseStateRequest Deserialize(MessageDeserializer deserializer) => new MoveToPoseStateRequest(deserializer);

        private MoveToPoseStateRequest(MessageDeserializer deserializer)
        {
            this.endEffecttorPose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.endEffecttorPose);
        }

        public override string ToString()
        {
            return "MoveToPoseStateRequest: " +
            "\nendEffecttorPose: " + endEffecttorPose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
