//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityMoveitPlanningInterface
{
    [Serializable]
    public class MoveToPoseStateResponse : Message
    {
        public const string k_RosMessageName = "unity_moveit_planning_interface/MoveToPoseState";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public MoveToPoseStateResponse()
        {
            this.success = false;
        }

        public MoveToPoseStateResponse(bool success)
        {
            this.success = success;
        }

        public static MoveToPoseStateResponse Deserialize(MessageDeserializer deserializer) => new MoveToPoseStateResponse(deserializer);

        private MoveToPoseStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "MoveToPoseStateResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
