//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityMoveitPlanningInterface
{
    [Serializable]
    public class PlanCartesianPathRequest : Message
    {
        public const string k_RosMessageName = "unity_moveit_planning_interface/PlanCartesianPath";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg[] wavepoints;

        public PlanCartesianPathRequest()
        {
            this.wavepoints = new Geometry.PoseMsg[0];
        }

        public PlanCartesianPathRequest(Geometry.PoseMsg[] wavepoints)
        {
            this.wavepoints = wavepoints;
        }

        public static PlanCartesianPathRequest Deserialize(MessageDeserializer deserializer) => new PlanCartesianPathRequest(deserializer);

        private PlanCartesianPathRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.wavepoints, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.wavepoints);
            serializer.Write(this.wavepoints);
        }

        public override string ToString()
        {
            return "PlanCartesianPathRequest: " +
            "\nwavepoints: " + System.String.Join(", ", wavepoints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
