//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.OnrobotVgControl
{
    [Serializable]
    public class SetCommandRequest : Message
    {
        public const string k_RosMessageName = "onrobot_vg_control/SetCommand";
        public override string RosMessageName => k_RosMessageName;

        public string command;

        public SetCommandRequest()
        {
            this.command = "";
        }

        public SetCommandRequest(string command)
        {
            this.command = command;
        }

        public static SetCommandRequest Deserialize(MessageDeserializer deserializer) => new SetCommandRequest(deserializer);

        private SetCommandRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "SetCommandRequest: " +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
