//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.OnrobotVgControl
{
    [Serializable]
    public class OnRobotVGInputMsg : Message
    {
        public const string k_RosMessageName = "onrobot_vg_control/OnRobotVGInput";
        public override string RosMessageName => k_RosMessageName;

        //  gVCA : Current vacuum value on Channel A.
        //         The vacuum is provided in 1/1000 of relative vacuum.
        //         Please note that this differs from the setpoint given in percent,
        //         as extra accuracy is desirable on the actual vacuum.
        public ushort gVCA;
        //  gVCB : Same as the one of channel A.
        public ushort gVCB;

        public OnRobotVGInputMsg()
        {
            this.gVCA = 0;
            this.gVCB = 0;
        }

        public OnRobotVGInputMsg(ushort gVCA, ushort gVCB)
        {
            this.gVCA = gVCA;
            this.gVCB = gVCB;
        }

        public static OnRobotVGInputMsg Deserialize(MessageDeserializer deserializer) => new OnRobotVGInputMsg(deserializer);

        private OnRobotVGInputMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gVCA);
            deserializer.Read(out this.gVCB);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.gVCA);
            serializer.Write(this.gVCB);
        }

        public override string ToString()
        {
            return "OnRobotVGInputMsg: " +
            "\ngVCA: " + gVCA.ToString() +
            "\ngVCB: " + gVCB.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
